### PR TITLE
Semantic Versioning support and pip fix

### PR DESCRIPTION
**Pull request by bilalshaikh42**
Ensures that a version file exists before attempting to read it. If no file exists, metadata.version will be set to None

### CODE REVIEW

**Comment by jonrkarr** [comment]
We could migrate over to this style. Wouldn't take much to switch all of the projects over.

I haven't seen much standardization over where version numbers are stored. I've see others use plain text like us.

**Comment by bilalshaikh42** [comment]
The current pull request would continue to use the old style by default, and only try to find the _version.py file if the VERSION file is not found. I think this should be backward-compatible and won't require any changes to other packages

**Comment by jonrkarr** [comment]
I see that, but we could make everything compatible with semantic versioning by switching to the new style

**Comment by bilalshaikh42** [comment]
@jonrkarr This is ready to merge in. It is switched completely to the new style, and tests have been updated. I've also changed the strategy to install packages to use a subprocess rather than the internal pip method. 
Can this be merged in? 
Will this cause breaks to other repositories before it is pushed to pip? I can update the karr_lab_build_utils to be compatible with this change as well

**Comment by jonrkarr** [comment]
I don't think this will cause any issues. I'll merge this when I have more time next week and update our other packages.

**Comment by jonrkarr** [comment]
Looks like pkg_utils will only look for version information in `_version.py`. I have made these additional changes to accommodate this:

- Additional changes to pkg_utils and other other packages
  - Renamed `pkg_utils/VERSION` to `pkg_utils/_version.py`
  - Added `__version__ = '...'` to `pkg_utils/_version.py`
  - Updated importing of version info into `pkg_utils/__init__.py`
  - Updated `package_data` to remove `VERSION` in `setup.py`
  - Updated reading of version info in `docs/conf.py`
  - Updated `MANIFEST.in`
- Additional changes to `pkg_utils`
  - Updated comments in `pkg_utils/core.py`
  - Updated documentation
- Additional changes to `karr_lab_build_utils`
  - Updated templates
  - Updated documentation

**Comment by jonrkarr** [comment]
I replaced using the unstable pip API in all of the `setup.py` scripts to use `subprocess` and `sys.executable`

**Pull request merged**
